cms/djangoapps/contentstore/views/course.py
cms/envs/common.py
cms/envs/devstack.py
common/djangoapps/student/views/dashboard.py
common/djangoapps/util/views.py
lms/djangoapps/discussion/views.py
lms/envs/common.py
openedx/core/djangoapps/content/course_overviews/models.py

This PR contains the following features:
- Enable Organizations (Organization_App)
- Enable Course Creator Group (ENABLE_CREATOR_GROUP)
- Filtering Courses w.r.t Organizations and Linked Courses

Enhance Multisite Feature w.r.t Organizations

---

cms/djangoapps/contentstore/views/organization.py

While course creation all organizations were listed down in the dropdown. This PR will restrict the organization list on the bases of site_configurations.

Filter organization wrt site_configurations on course creation

---

cms/djangoapps/contentstore/views/course.py
cms/djangoapps/contentstore/views/organization.py
cms/envs/common.py
cms/envs/devstack.py
common/djangoapps/student/views/dashboard.py
common/djangoapps/third_party_auth/colaraz.py
common/djangoapps/third_party_auth/identityserver3.py
common/djangoapps/third_party_auth/models.py
common/djangoapps/third_party_auth/tests/test_identityserver3.py
common/djangoapps/third_party_auth/tests/testutil.py
common/djangoapps/util/views.py
lms/djangoapps/discussion/views.py
lms/envs/common.py
lms/envs/production.py
openedx/core/djangoapps/content/course_overviews/models.py

Using develop branch for further development.

merging colaraz_master into develop

---

lms/urls.py
openedx/features/colaraz_features/api/fields.py
openedx/features/colaraz_features/api/serializers.py
openedx/features/colaraz_features/api/urls.py
openedx/features/colaraz_features/api/validators.py
openedx/features/colaraz_features/api/views.py
openedx/features/colaraz_features/helpers.py
openedx/features/colaraz_features/urls.py

**Jira Story:**  [EDE-318](https://edlyio.atlassian.net/browse/EDE-318)
This PR creates a REST endpoint that allows its consumers to create a site, organization, site theme and site configuration in a single API call.

feat: Adding API for site, organisation, theme and site configuration creation.

---

cms/templates/widgets/user_dropdown.html
common/djangoapps/student/views/dashboard.py
common/djangoapps/third_party_auth/settings.py
lms/templates/courseware/course_about.html
lms/templates/header/user_dropdown.html
lms/templates/user_dropdown.html
openedx/features/colaraz_features/auth_pipeline.py
openedx/features/colaraz_features/helpers.py
openedx/features/colaraz_features/urls.py
openedx/features/colaraz_features/views.py

https://edlyio.atlassian.net/browse/EDE-388
Redirecting user to Social Auth Provider for the Logout process. The auth-provider logout's user from all services included open edX using an iFrame.

Changing Logout Process

---

openedx/features/colaraz_features/admin.py

Register ColarazUserProfile model to the admin panel.

register ColarazUserProfile model to admin panel

---

common/static/common/templates/discussion/forum-actions.underscore
common/static/common/templates/discussion/thread-response-show.underscore
common/static/common/templates/discussion/thread.underscore
lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html

This PR contains new designs for discussion response.
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-391
**Merge checklist:**
**Post merge:**

Discussion response template new design implimenteed

---

cms/templates/widgets/user_dropdown.html
cms/urls.py
common/djangoapps/student/views/dashboard.py
lms/templates/courseware/course_about.html
lms/templates/header/user_dropdown.html
lms/templates/user_dropdown.html
lms/urls.py

https://edlyio.atlassian.net/browse/EDE-427
Changing the logout process on studio. Now the logout process will be governed by IdP with respect to the site-specific domains.
**Note**: Now we have to add 'LMS_BASE' and 'CMS_BASE' in site configurations of each site.

change studio logout urls and add namespace for colaraz_features

---

common/djangoapps/student/roles.py
common/djangoapps/student/views/dashboard.py
lms/envs/common.py
lms/templates/courseware/course_about.html
openedx/features/colaraz_features/filters.py
openedx/features/colaraz_features/forms.py
openedx/features/colaraz_features/helpers.py
openedx/features/colaraz_features/permissions.py
openedx/features/colaraz_features/templates/course-access-roles-create.html
openedx/features/colaraz_features/templates/course-access-roles-delete.html
openedx/features/colaraz_features/templates/course-access-roles-list.html
openedx/features/colaraz_features/templates/course-access-roles-update.html
openedx/features/colaraz_features/urls.py
openedx/features/colaraz_features/views.py

**JIRA Ticket:** [EDE-359](https://edlyio.atlassian.net/browse/EDE-359)
__Description:__
Universities/Companies using as LMS and adding, maintaining their own content. Require a specific, scaled-down/restricted view at the university/company level. Where the individual can grant role permissions/update at his level instead of asking it to the Colaraz Admin.
__Acceptance Criteria:__
1. Create a page for user management
2. Verify that university admin can grant permission to his own university members.
__Note:__
I have not added validations related to business logic, those can be added later after some discovery on what validations to apply and what to do in cases of conflicts.

EDE-359: UI to perform CRUD on course access roles.

---

lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html

Colaraz course discussion Instructor dropdown added .
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-390
**Merge checklist:**
**Post merge:**

Instructor drop down button added

---

openedx/features/colaraz_features/middlewares.py

https://edlyio.atlassian.net/browse/EDE-413
If a user belonging to Site A and tries to enter Site B he will be redirected to Site A.

redirect user to his lms site domain on entering wrong domain

---

lms/envs/production.py

[EDE-453](https://edlyio.atlassian.net/browse/EDE-453)
Dynamically update navbar urls. The URLs are different for different sites and different environments that's why we can't hardcode them in theme

update navbar urls

---

lms/djangoapps/courseware/courses.py
openedx/core/lib/xblock_utils/__init__.py

[EDE-473](https://edlyio.atlassian.net/browse/EDE-473)
Changing cms_base depending on site configurations

feedback changes regarding cms_base

---

openedx/features/colaraz_features/auth_pipeline.py

[EDE-482](https://edlyio.atlassian.net/browse/EDE-482)
Course creator instance needed to be created to give course creation access to user.

Add course creator instance while social auth process

---

openedx/features/colaraz_features/templates/course-access-roles-create.html
openedx/features/colaraz_features/templates/course-access-roles-delete.html
openedx/features/colaraz_features/templates/course-access-roles-list.html
openedx/features/colaraz_features/templates/course-access-roles-update.html

**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-451
**Merge checklist:**
**Post merge:**

Client feedback for Course privileges

---

openedx/features/colaraz_features/templates/course-access-roles-delete.html

Course Privileges view updates

---

lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html
lms/djangoapps/discussion/views.py

[EDE-473](https://edlyio.atlassian.net/browse/EDE-473)
Adding course details on discussion page

add course details on discussion page

---

openedx/features/colaraz_features/auth_pipeline.py

Colaraz's IdP has changed a bit so replacing "Company Admin" with "LMS admin" accordingly.

Replace "Company Admin" with "LMS admin"

---

openedx/features/colaraz_features/auth_pipeline.py

"LMS admin" is changed to "LMS Admin"

captalize a

---

openedx/features/colaraz_features/auth_pipeline.py

Hot Fix: Capitalize "a" of "admin"

release-2020-05-14.1

---

openedx/features/colaraz_features/api/views.py

[EDE-457](https://edlyio.atlassian.net/browse/EDE-457)
https://github.com/colaraz/edx-platform/pull/59
Adding authentication and permission classes

add authentication and permission classes for notifications api

---

openedx/features/colaraz_features/auth_pipeline.py
openedx/features/colaraz_features/constants.py
openedx/features/colaraz_features/filters.py
openedx/features/colaraz_features/forms.py
openedx/features/colaraz_features/helpers.py
openedx/features/colaraz_features/templates/course-access-roles-list.html
openedx/features/colaraz_features/templates/course-access-roles-update.html
openedx/features/colaraz_features/urls.py
openedx/features/colaraz_features/views.py

[COL-33](https://edlyio.atlassian.net/browse/COL-33)
[COL-92](https://edlyio.atlassian.net/browse/COL-92)
[COL-93](https://edlyio.atlassian.net/browse/COL-93)
Refactoring User Roles Management Panel.

User Role Management Panel

---

openedx/features/colaraz_features/api/views.py

https://edlyio.atlassian.net/browse/COL-142
Add ENABLED flag in Notifications and Job Alerts APIs

Add ENABLED flag in Notifcations and Job Alerts APIs

---

lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html

**Story Links**
[COl-98](https://edlyio.atlassian.net/browse/COL-98)
**PR Link with theme**
https://github.com/colaraz/colaraz-theme/pull/58
will be adding load more button on the bottom of the dropdown

Implement Discussion Forum Filters

---

lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html

Story Links 
[COL-125](https://edlyio.atlassian.net/browse/COL-125)
PR Links
[Colaraz Theme](https://github.com/colaraz/colaraz-theme/pull/69)
description: 
added the search input box in the all discussion dropdown and put functionality in the theme PR

Search Functionality in Discussion Forum

---

common/static/common/js/discussion/views/discussion_content_view.js
common/static/common/templates/discussion/thread.underscore
lms/djangoapps/discussion/templates/discussion/discussion_profile_page.html
lms/djangoapps/discussion/views.py
openedx/features/colaraz_features/helpers.py

https://edlyio.atlassian.net/browse/COL-120
Using User's Profile name instead of username (due to colaraz requirements) and dynamically placing data.

Populating user fullname (profile name) dynamically on discussions

---

common/static/common/js/discussion/views/discussion_thread_view.js
common/static/common/js/discussion/views/thread_response_view.js
lms/djangoapps/discussion/views.py
lms/djangoapps/django_comment_client/utils.py
openedx/features/colaraz_features/helpers.py

https://edlyio.atlassian.net/browse/COL-157
In Colaraz, User's username field isn't being used to show User's name, we are using UserProfile's Name field instead. So, for that reason we have to add UserProfile's name in discussion thread.

setting user fullname in discussion threads

---

openedx/features/colaraz_features/templates/course-access-roles-delete.html
openedx/features/colaraz_features/templates/course-access-roles-update.html
openedx/features/colaraz_features/views.py

https://edlyio.atlassian.net/browse/COL-33
This PR contains three fixes:
* Add Cancel Button on delete page
* Remove Course-Id selection field from Org-roles
* Raise 404 errors instead of 500

User role management panel feedback changes

---

common/static/common/js/discussion/views/discussion_content_view.js
lms/djangoapps/django_comment_client/utils.py
openedx/features/colaraz_features/helpers.py

https://edlyio.atlassian.net/browse/COL-157
Replace Endorser's username with UserProfile name.

replace endorser name with his fullname

---

lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html

Ticket link
[COL-167](https://edlyio.atlassian.net/browse/COL-167)
Colaraz theme Link: https://github.com/colaraz/colaraz-theme/pull/78
description: solved the QA reported issues here

Fixed QA issues on Discussion Filter

---

lms/templates/discussion/_underscore_templates.html

HOTFIX: New course creation discussion crash

FIX: new course discussion crash

---

lms/static/js/instructor_dashboard/membership.js

This PR is related to [https://edlyio.atlassian.net/browse/COL-173](https://edlyio.atlassian.net/browse/COL-173)
Removing usernames from the instructor dashboard.
**Related PR**
[https://github.com/colaraz/colaraz-theme/pull/81](https://github.com/colaraz/colaraz-theme/pull/81)

COL-173 Remove username from instructor dashboard

---

lms/djangoapps/verify_student/models.py
lms/envs/common.py
openedx/features/colaraz_features/apps.py
openedx/features/colaraz_features/management/commands/verify_all_users.py
openedx/features/colaraz_features/signals.py

This PR is related to [https://edlyio.atlassian.net/browse/COL-184](https://edlyio.atlassian.net/browse/COL-184)
Skip the usual student verification step. Automatically verify a user as soon as the user has registered.
Set the verification expiration date to max possible date.
**Reference PRs**
[https://github.com/ucsd-ets/edx-platform/pull/261](https://github.com/ucsd-ets/edx-platform/pull/261)
[https://github.com/ucsd-ets/edx-platform/pull/263](https://github.com/ucsd-ets/edx-platform/pull/263)

COL-184 Add automatic account verification for the user

---

lms/djangoapps/instructor/views/instructor_dashboard.py

This PR is related to [https://edlyio.atlassian.net/browse/COL-181](https://edlyio.atlassian.net/browse/COL-181)
Right now, we are not using the `is_staff` flag of edx default in `colaraz`. We are making those staff-level decisions on the basis of course access roles. The same thing has been implemented for `certificate` tab of the `instructor dashboard`.
We have updated this check for this line 
[https://github.com/colaraz/edx-platform/blob/develop/lms/djangoapps/instructor/views/instructor_dashboard.py#L198](https://github.com/colaraz/edx-platform/blob/develop/lms/djangoapps/instructor/views/instructor_dashboard.py#L198)

COL-181 Modify is_staff check for certificates

---

lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html

Story Link
[COL-175](https://edlyio.atlassian.net/browse/COL-175)
description updated ids
PR link for theme: https://github.com/colaraz/colaraz-theme/pull/94

No More Posts Element Glitch Fix

---

cms/djangoapps/contentstore/views/library.py
cms/static/js/index.js
cms/static/js/views/utils/create_course_utils.js
cms/static/js/views/utils/create_library_utils.js
cms/static/js/views/utils/create_utils_base.js

This PR is related to [https://edlyio.atlassian.net/browse/COL-161](https://edlyio.atlassian.net/browse/COL-161)
In this PR the organization drop-down menu for the content library has been added.
**Related PR**
[https://github.com/colaraz/colaraz-theme/pull/99](https://github.com/colaraz/colaraz-theme/pull/99)

COL-161 Add organization dropdown for library creation

---

openedx/features/colaraz_features/api/views.py

https://edlyio.atlassian.net/browse/COL-209

Bug Fix: Handling Job Alerts API exception

---

lms/static/certificates/sass/_components.scss

This PR is related to [https://edlyio.atlassian.net/browse/COL-210](https://edlyio.atlassian.net/browse/COL-210)
This  includes
#113 Handling Job Alerts API Exception 
#115 Show signature and certificate top logo

release-2020-08-07

---

openedx/features/colaraz_features/templates/course-access-roles-create.html
openedx/features/colaraz_features/templates/course-access-roles-delete.html
openedx/features/colaraz_features/templates/course-access-roles-layout.html
openedx/features/colaraz_features/templates/course-access-roles-list.html
openedx/features/colaraz_features/templates/course-access-roles-update.html

###Story Link
https://edlyio.atlassian.net/browse/COL-218
###Description
Changing title of course privileges panel

Changing title of course privileges panel

---

openedx/features/colaraz_features/api/fields.py
openedx/features/colaraz_features/api/serializers.py
openedx/features/colaraz_features/api/urls.py
openedx/features/colaraz_features/api/validators.py
openedx/features/colaraz_features/api/views.py
openedx/features/colaraz_features/helpers.py

https://edlyio.atlassian.net/browse/COL-183

Site creation API

---

openedx/features/colaraz_features/auth_backend.py
openedx/features/colaraz_features/helpers.py

https://edlyio.atlassian.net/browse/COL-183
* removing typo
* catching exception for IdP

removing a typo and raising exception in-case user details in not provided through IdP

---

lms/envs/common.py
lms/envs/production.py
openedx/features/colaraz_features/api/serializers.py
openedx/features/colaraz_features/api/validators.py
openedx/features/colaraz_features/api/views.py

https://edlyio.atlassian.net/browse/COL-183
Replacing OAuth based authentication with token-based authentication

using api auth token for site creation api

---

cms/envs/common.py

Ticket:
https://edlyio.atlassian.net/browse/COL-232
Description:
Increased file size limit in course content file upload menu. By default size was 10MB. Now it is increased till 50MB.

increased file size limit

---

openedx/features/colaraz_features/api/tests/tests.py
openedx/features/colaraz_features/api/urls.py
openedx/features/colaraz_features/api/views.py
openedx/features/colaraz_features/urls.py

Ticket:
https://edlyio.atlassian.net/browse/COL-234
Description:
Developed an api which will return course outline in sequence(tree structure).

course outline api

---

openedx/features/colaraz_features/api/urls.py
openedx/features/colaraz_features/api/views.py

Ticket:
https://edlyio.atlassian.net/browse/COL-235
Description:
Develop the xblock api which return html response on token base authentication.

token base xblock api

---

requirements/edx/development.txt

Ticket:
https://edlyio.atlassian.net/browse/COL-241
Description:
course import was giving error of scorm xblock plugin missing. So, added requirement in development.txt to install scorm-xblock.

added scorm xblock package in development.txt

---

requirements/edx/base.txt

Ticket:
https://edlyio.atlassian.net/browse/COL-241
Description:
Added scorm xblock requirement in base.txt. This requirement is already present in development.txt which didn't worked on stage server.

added scorm xblock in base.txt

---

cms/envs/common.py

Ticket:
https://edlyio.atlassian.net/browse/COL-232
Description:
Recently, file size was increased up-to 50MB. Now, it is requested to increase the file size up-to 500MB.

increased asset file size upto 500 mb

---

openedx/features/colaraz_features/api/urls.py
openedx/features/colaraz_features/api/views.py

ticket:
https://edlyio.atlassian.net/browse/COL-244
description:
xblock callback handle api to do xblock submissions.

xblock callback handler api

---

openedx/core/djangoapps/user_authn/views/register.py
openedx/features/colaraz_features/auth_backend.py
openedx/features/colaraz_features/helpers.py

Register user from AuthExchangeView if the user already doesn't exist. 
Ticket Link: https://edlyio.atlassian.net/browse/COL-238

COL-238 User Registration API for Mobile

---

common/lib/xmodule/xmodule/js/src/capa/display.js

https://edlyio.atlassian.net/browse/COL-269
hide progress

removes progress

---

openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html

**Removed "Mailing Address"**
Story: [COL-273](https://edlyio.atlassian.net/browse/COL-273?atlOrigin=eyJpIjoiOTUwMzc2NjQ1YTcwNGRmNDkwZjM5NDA0ZjE5OTlhNzAiLCJwIjoiaiJ9)
Removed the dangling text "Our mailing address is" from email template.

Removed Mailing address text

---

openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html

Reverts colaraz/edx-platform#141

Revert "Removed Mailing address text"

---

lms/djangoapps/instructor_task/tasks_helper/grades.py

**Display Grades in Percentage**
Story: [COL-264](https://edlyio.atlassian.net/browse/COL-264?atlOrigin=eyJpIjoiODc0NTNkOTYzNDMxNDA5MzkwYjExMTZhMDRlNWZkOWYiLCJwIjoiaiJ9)
Change grades form decimal value to percentage in Problem Grade Reports. 
i.e 0.5 -> 50.0%

Displayed grades in percentage

---

requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in
requirements/edx/testing.txt

[COL-299](https://edlyio.atlassian.net/browse/COL-299)
We have forked edx-sga under colaraz and change the upload limit there. This PR will upgrade the edx-sga in requirement files to use our own forked repo.

upgrade edx-sga to use colaraz fork

---

requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in
requirements/edx/testing.txt

[COL-300](https://edlyio.atlassian.net/browse/COL-300)

COL-300 Bump version of edx-sga

---

lms/djangoapps/instructor_task/tasks_helper/grades.py
lms/envs/common.py
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in
requirements/edx/testing.txt

Merging develop back to master.

Release candidate

---

requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in
requirements/edx/testing.txt

Relevant Ticket: https://edlyio.atlassian.net/browse/COL-290
Description: Adds long question xblock to edx-platform

Add long question xblock in edx platform

---

requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in
requirements/edx/testing.txt

Relevant Ticket: https://edlyio.atlassian.net/browse/COL-290
Description: Updated long answer xblock release version

Update long answer xblock version

---

requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in
requirements/edx/testing.txt

Reverts colaraz/edx-platform#154

Revert "Update long answer xblock version"

---

common/lib/xmodule/xmodule/course_module.py
conf/locale/ar/LC_MESSAGES/django.po
conf/locale/en/LC_MESSAGES/django.po
conf/locale/eo/LC_MESSAGES/django.po
conf/locale/es_419/LC_MESSAGES/django.po
conf/locale/fr/LC_MESSAGES/django.po
conf/locale/he/LC_MESSAGES/django.po
conf/locale/hi/LC_MESSAGES/django.po
conf/locale/ko_KR/LC_MESSAGES/django.po
conf/locale/mn/LC_MESSAGES/django.po
conf/locale/pt_BR/LC_MESSAGES/django.po
conf/locale/rtl/LC_MESSAGES/django.po
conf/locale/ru/LC_MESSAGES/django.po
conf/locale/zh_CN/LC_MESSAGES/django.po
conf/locale/zh_HANS/LC_MESSAGES/django.po

Typo issues are fixed. 'edX' is replaced with 'Colaraz LMS'.

Typo Issues fixing

---

cms/templates/studio_xblock_wrapper.html

Issue of csv files conversion to xls in Studio fixed.

Wrong format for CSV issue fixed in Studio
