colaraz/edx-platform

common/djangoapps/third_party_auth/identityserver3.py, common/djangoapps/third_party_auth/tests/test_identityserver3.py, common/djangoapps/third_party_auth/tests/testutil.py, lms/envs/production.py
* Add IdentityServer3 Backend
This adds a backend for users who want to use IdentityServer3 as their
SSO provider. It can be used with the OAuth2ProviderConfig in django
admin to point to an external provider.
Note: This backend will be used as a base backend for us.
=> Add IdentityServer3 Backend

common/djangoapps/third_party_auth/colaraz.py, common/djangoapps/third_party_auth/models.py, lms/envs/production.py
This PR contains a custom Backend compatible with Colaraz's IdP.
We can't use same backend with different sites so, I have made a small change in models.py to skip filtering of backends on the basis of sites.
=> Create custom backend for Colaraz IdP

cms/envs/common.py, common/djangoapps/student/helpers.py, lms/envs/common.py, openedx/core/djangoapps/user_authn/views/register.py
https://edlyio.atlassian.net/browse/EDE-326
As Colaraz has implemented OAUTH based IdP, the User was able to register new accounts through the open edX registration flow. 
This PR will restrict the creation of new accounts through open edX.
We have to use 'ALLOW_PUBLIC_ACCOUNT_CREATION' feature with some customization in its usage.
By default 'ALLOW_PUBLIC_ACCOUNT_CREATION' restricts us to create an account through open edX registration as well as through IdP, which in our case wasn't a desired functionality.
In lms.env.json under FEATURES:
"ALLOW_PUBLIC_ACCOUNT_CREATION" : false
=> Restrict user account creation to social_auth only

common/djangoapps/student/views/dashboard.py, lms/envs/production.py, openedx/features/colaraz_features/auth_backend.py
Moving Colaraz's auth backend to colaraz_features app and filtering courses on the bases of organization short name.
=> moving auth backend to colaraz app and filtering on org short name

openedx/features/colaraz_features/api/serializers.py, openedx/features/colaraz_features/api/validators.py, openedx/features/colaraz_features/helpers.py
__Description:__
This PR contains fixes for the following
1. 500 errors on the staging server. This error was being caused by `Site.name` max length constraint, I have added the same constraint on the serializer so that we catch such error invalidation.
2. Domain name validation was letting invalid domains pass through, updated the validation logic so that only valid domains are passing through the validation logic.
=> fix: Fixes 500 errors and the bug of letting invalid domains pass.

cms/envs/devstack.py, openedx/features/colaraz_features/middlewares.py
This PR contains the following content:
* Removing an unused import 
* Turning off ENABLE_CREATOR_GROUP flag (now developer need to turn it on by using a private.py for devstack)
=> Turning off ENABLE_CREATOR_GROUP flag

openedx/features/colaraz_features/api/serializers.py
__Description:__
I forgot to adjust max_length restriction taking "courses" and "studio" prefixes into account in my previous PR, this PR fixes that.
I could not test it before as the bug is not reproducible locally, it only appears on stage.
=> EDE-318: Take site prefix into account while validating max_length of name and domain

cms/djangoapps/contentstore/views/course.py, cms/static/js/index.js, cms/static/js/models/settings/course_details.js, cms/static/js/views/settings/main.js, cms/static/sass/views/_dashboard.scss, cms/static/sass/views/_settings.scss, cms/templates/index.html, cms/templates/settings.html, common/djangoapps/util/organizations_helpers.py
**Ticket Link:** https://edlyio.atlassian.net/browse/EDE-358
**Description:** 
- Staff users can select multiple secondary organizations while creating a course.
- Staff users can edit secondary organizations in the course setting page.
=> Secondary organizations on course create and setting page

cms/djangoapps/contentstore/views/course.py, common/djangoapps/util/organizations_helpers.py
**Ticket is related to**: https://edlyio.atlassian.net/browse/EDE-358
Use organization **short_name** instead of **name** as edX is using the short_name for the primary organization.
=> fix bug for secondary organizations => use short_name instead name

openedx/features/colaraz_features/api/serializers.py
__Description:__
This PR adds defaults for optional fields to avoid key errors later on. Also, I have marked `site_name` as it is not used anywhere.
=> EDE-318: provide a default value for optional fields so that error is not raised later on.

cms/djangoapps/contentstore/utils.py
This PR is related to [https://edlyio.atlassian.net/browse/EDE-412](https://edlyio.atlassian.net/browse/EDE-412)
The preview functionality is not achievable due to the current implementation of colaraz middleware and the URLs patterns that we are using right now for different sites.
=> Comment out the preview functionality

cms/templates/index.html
Ticket Link: Bugfix for https://edlyio.atlassian.net/browse/EDE-358
**Description:** 
**Before:**
**After:**
=> Remove required sign (*) from secondary organizations input field.

lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html
This PR is related to [EDE-443](https://edlyio.atlassian.net/browse/EDE-443)
The HTML portion responsible for course details displaying on the sidebar, has been removed. Now it is rendered from another file named **course_details_sidebar.html** which is located in **colaraz_theme** directory.
PR link for **colaraz_theme**
[https://github.com/colaraz/colaraz-theme/pull/13/](https://github.com/colaraz/colaraz-theme/pull/13/)
**Discussion Page**
=> EDE-443 Integrate course details page

cms/djangoapps/course_creators/models.py, openedx/features/colaraz_features/constants.py, openedx/features/colaraz_features/exceptions.py, openedx/features/colaraz_features/fields.py, openedx/features/colaraz_features/filters.py, openedx/features/colaraz_features/forms.py, openedx/features/colaraz_features/helpers.py, openedx/features/colaraz_features/models.py, openedx/features/colaraz_features/templates/course-access-roles-create.html, openedx/features/colaraz_features/templates/course-access-roles-delete.html, openedx/features/colaraz_features/templates/course-access-roles-list.html, openedx/features/colaraz_features/templates/course-access-roles-update.html, openedx/features/colaraz_features/urls.py, openedx/features/colaraz_features/views.py
**JIRA Ticket:** [EDE-433](https://edlyio.atlassian.net/browse/EDE-433)
The role management page needs some UX improvements, currently, it works as expected but it is time-consuming to assign multiple roles to the user.
**Acceptance Criteria:**
- Add search capability based on email for the roles list page
- Convert the email char field to a searchable select field.
- Make course-id field multi-char field so that more than one course can be entered.
- Convert organization dropdown to multi-select checkboxes field.
- Users should only be able to view emails in the first select field from their organization.
- Users should get an error if he tries to add a role for a course not in its organization.
- Added a new role lms_admin on creating a page that improves UX for Coalraz …
=> EDE-433: UX improvements for course access roles admin page 

cms/djangoapps/contentstore/views/course.py, cms/djangoapps/contentstore/views/organization.py, common/djangoapps/util/organizations_helpers.py
**Ticket Link:**  https://edlyio.atlassian.net/browse/EDE-470
Alter secondary organization input options while creating and editing a course.
- **To admin user:**
- Show all organizations as a secondary organization input option.
- **To normal staff user:**
- Restrict user to only authorized site organizations (configured from site-config).
=> filter seconday organizations

openedx/features/colaraz_features/auth_pipeline.py
[EDE-508](https://edlyio.atlassian.net/browse/EDE-508)
course_creator_org doesn't require an organization name in course access role, it gives an error if an organization is given while creating course.
=> FIX: remove organization from course creator group

cms/envs/production.py, lms/envs/production.py, openedx/features/colaraz_features/api/urls.py, openedx/features/colaraz_features/api/views.py
[EDE-457](https://edlyio.atlassian.net/browse/EDE-457)
Integrating Colaraz's Site Notifications API with open edX.
Main use-cases:
1) Refresh and populate notifications from API endpoint to front-end navbar
2) Once clicked on the navbar mark the unread notifications as read.
=> Integrate Notifications API

openedx/features/course_experience/templates/course_experience/course-home-fragment.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-84](https://edlyio.atlassian.net/browse/COL-84)
Previously the course header on course details page shows static data. Now it has been integrated to display dynamic data according to the course.
**If the image is set**
**If the image is not set**
=> COL-84 Integrate course header

lms/djangoapps/courseware/tests/test_courses.py, lms/djangoapps/courseware/tests/test_module_render.py, lms/envs/common.py, openedx/core/djangoapps/content/course_overviews/tests/test_course_overviews.py, openedx/core/lib/courses.py, openedx/core/lib/tests/test_courses.py, openedx/features/course_experience/templates/course_experience/course-home-fragment.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-99](https://edlyio.atlassian.net/browse/COL-99)
**Description**
By default, if we don't set up an edX course image it comes up with a broken image URL. In this PR we have added a default course functionality. If a staff user doesn't set up a course image for the first time, a default course image will be shown.
**Dependency**
The PR is dependent on this PR [https://github.com/colaraz/colaraz-theme/pull/51](https://github.com/colaraz/colaraz-theme/pull/51)
In the PR, mentioned above, default course image files have been added.
**Reference PRs**
1. [https://github.com/ucsd-ets/edx-platform/pull/274/](https://github.com/ucsd-ets/edx-platform/pull/274/)
2. [https://github.com/ucsd-ets/edx-platform/pull/275/](https://github.com/ucsd …
=> COL-99 fix course default image issue

lms/static/js/Markdown.Editor.js
This PR is related to [https://edlyio.atlassian.net/browse/COL-111](https://edlyio.atlassian.net/browse/COL-111)
Previously, when we try to respond a comment in a thread just using an image the submit button wasn't enabled. 
Now this behavior has been fixed.
**Old Behavior**
**New Behavior**
=> COL-111 Fix add response submit button

common/static/common/js/discussion/views/discussion_thread_view.js, common/static/common/js/discussion/views/new_post_view.js, common/static/common/js/discussion/views/thread_response_view.js, common/static/common/templates/discussion/new-post.underscore, common/static/common/templates/discussion/thread-response.underscore, common/static/common/templates/discussion/thread.underscore, lms/static/js/Markdown.Editor.js
This PR is related to [https://edlyio.atlassian.net/browse/COL-124](https://edlyio.atlassian.net/browse/COL-124)
Maintaining a disabled submit button feature was causing some other issues. So, in this PR all changes related to that feature have been removed. 
**Reference PR's**
Changes related to these PR's have been removed.
[https://github.com/edly-io/edx-platform/pull/27/files](https://github.com/edly-io/edx-platform/pull/27/files)
[https://github.com/edly-io/edx-platform/pull/28/files](https://github.com/edly-io/edx-platform/pull/28/files)
[https://github.com/edly-io/edx-platform/pull/29/files](https://github.com/edly-io/edx-platform/pull/29/files)
[https://github.com/colaraz/edx-platform/pull/68/files](https://github.com/colaraz/edx-platform/pull/68/files)
=> COL-124 Rollback to edX default functionality of posts submit button

common/static/common/js/discussion/views/discussion_content_view.js
This PR is related to [https://edlyio.atlassian.net/browse/COL-122](https://edlyio.atlassian.net/browse/COL-122)
We are no more using edX user profile in colaraz. But on the discussion page there are still some links referring to profile pages. In this PR these links have been deactivated. They are no more clickable.
=> COL-122 Replace author links on posts with simple text

common/static/common/js/discussion/utils.js
This PR is related to [https://edlyio.atlassian.net/browse/COL-124](https://edlyio.atlassian.net/browse/COL-124)
In the PR [https://github.com/colaraz/edx-platform/pull/70](https://github.com/colaraz/edx-platform/pull/70) we forgot to remove some code related to disabled submit button feature. Due to which there occurs some errors. Now that code portion has been removed in this PR.
**Reference PR**
[https://github.com/edly-io/edx-platform/pull/34/files](https://github.com/edly-io/edx-platform/pull/34/files)
=> COL-124 Remove remaining code related to disabled submit button feature

common/static/common/templates/discussion/thread.underscore
Story Links
[COL-120](https://edlyio.atlassian.net/browse/COL-120)
Desciption: static text is now fetched by variables
=> Static Author and Date Display Corrected

common/static/common/templates/discussion/thread.underscore
Reverts colaraz/edx-platform#79
mistakenly merged the PR 79 , reverting it as it need more work to do
=> Revert "Static Author and Date Display Corrected"

common/static/common/js/discussion/views/discussion_content_view.js, lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-158](https://edlyio.atlassian.net/browse/COL-158)
Because of the change in the design proposed by colaraz, the voting functionality of edX discussions was not working. This thing has been fixed in this PR.
**Related PR of theme repo**
[https://github.com/colaraz/colaraz-theme/pull/73](https://github.com/colaraz/colaraz-theme/pull/73)
=> COL-158 Add voting functionality

common/static/common/templates/discussion/thread.underscore, lms/templates/discussion/_underscore_templates.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-159](https://edlyio.atlassian.net/browse/COL-159)
Because of the redesigning of `discussion` page, the `follow post` functionality was broken. Now it has been fixed.
**Related PR**
This PR is dependent on the PR from `colaraz/edx theme`
[https://github.com/colaraz/colaraz-theme/pull/77](https://github.com/colaraz/colaraz-theme/pull/77)
=> COL-159 Add follow post functionality

common/static/common/js/discussion/views/discussion_thread_list_view.js, lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-174](https://edlyio.atlassian.net/browse/COL-174)
Previously, the voting and post following functionality wasn't working for `unit level discussion`. Now this functionality has been added.
**Related PR**
[https://github.com/colaraz/colaraz-theme/pull/82](https://github.com/colaraz/colaraz-theme/pull/82)
=> COL-174 Fix unit level discussion issue

common/static/common/js/discussion/views/discussion_content_view.js
This PR is related to [https://edlyio.atlassian.net/browse/COL-174](https://edlyio.atlassian.net/browse/COL-174)
Previously, we weren't setting the first time status of the `voting` button. It was always set to `false`. Means, whenever we clicked on that button, the first voting request was always of `upvote`. This thing has been fixed in this PR.
=> COL-174 Fix first time vote button status

common/static/common/js/discussion/views/discussion_content_view.js
This PR is related to [https://edlyio.atlassian.net/browse/COL-174](https://edlyio.atlassian.net/browse/COL-174)
Using `let` to make js variable was causing build failure issues. Now it has been replaced with `var`.
=> Use var to make js variable

lms/static/js/instructor_dashboard/membership.js, lms/static/js/instructor_dashboard/student_admin.js
This PR is related to [https://edlyio.atlassian.net/browse/COL-173](https://edlyio.atlassian.net/browse/COL-173)
In these PRs
[https://github.com/colaraz/colaraz-theme/pull/81](https://github.com/colaraz/colaraz-theme/pull/81)
[https://github.com/colaraz/edx-platform/pull/91/](https://github.com/colaraz/edx-platform/pull/91/)
We removed the `username` from the instructor dashboard. But we forgot to update the error messages.
Now this thing has been fixed in this PR.
=> Remove username from error messages of instructor dashboard

lms/djangoapps/instructor/views/instructor_dashboard.py
This PR is related to [https://edlyio.atlassian.net/browse/COL-181](https://edlyio.atlassian.net/browse/COL-181)
In the PR [https://github.com/colaraz/edx-platform/pull/103](https://github.com/colaraz/edx-platform/pull/103)
We did some modifications which were responsible to show certificate tab to the instructor of the course. But in the QA, we identified that these modifications are not enough to make the options (shown in the certificates tab) fully functional for the user whose role is an instructor. So for the release purposes, we are reverting these incomplete changes.
=> COL-181 Revert is_staff modifications for certificates tab

lms/static/js/certificates/models/certificate_exception.js, lms/static/js/certificates/models/certificate_invalidation.js, lms/templates/instructor/instructor_dashboard_2/certificate-invalidation.underscore, lms/templates/instructor/instructor_dashboard_2/certificate-white-list-editor.underscore
This PR is related to [https://edlyio.atlassian.net/browse/COL-188](https://edlyio.atlassian.net/browse/COL-188)
Previously, when we removed `username` from the instructor dashboard, the certificates weren't enabled that's why we missed this page. Now the certificates page has also been updated.
**Related PR**
[https://github.com/colaraz/colaraz-theme/pull/93](https://github.com/colaraz/colaraz-theme/pull/93)
=> COL-188 Remove username word from certificates tab

cms/djangoapps/contentstore/views/certificates.py, common/djangoapps/util/views.py, lms/djangoapps/instructor/views/api.py, lms/djangoapps/instructor/views/instructor_dashboard.py, openedx/features/colaraz_features/helpers.py
This PR is related to [https://edlyio.atlassian.net/browse/COL-181](https://edlyio.atlassian.net/browse/COL-181)
Previously `Certifications` tab functionality was dependent on `is_staff`. Now this thing has been made compatible to Colaraz Roles.
=> COL-181 Replace is_staff privileges

openedx/core/djangoapps/user_authn/views/logout.py
This PR is related to [https://edlyio.atlassian.net/browse/COL-208](https://edlyio.atlassian.net/browse/COL-208)
Previously, when we try to logout from the LMS side it will make the user logout from the IdP but it will not log out the user from the other services including eCommerce e.t.c. Currently, when we tried to log out from the LMS the control goes to IdP
and it opens `/logout` of LMS but due to xframe-option-restriction, this step isn't succeeded due to which remain login to other services. Now, this thing has been fixed in this PR.
=> COL-208 Fix logout behavior from lms side

lms/djangoapps/courseware/views/views.py
https://edlyio.atlassian.net/browse/COL-233
when xblock is rendered loading dots are not disappearing
Open any xblock
=> change flag to render div which is used to hide loading dots

openedx/features/colaraz_features/api/urls.py, openedx/features/colaraz_features/api/validators.py, openedx/features/colaraz_features/api/views.py
Ticket:
https://edlyio.atlassian.net/browse/COL-235
Description:
Added auth token in url as query parameter which is being verified and authenticated via custom authenticator.
Example url format:
{domain_name}/colaraz/api/v1/xblock/{block_usage_id}/?token=AIlgBSplKjY8XNkxtcN45aABemoTnI
=> add token in url of xblock api

openedx/features/colaraz_features/api/validators.py
Ticket:
https://edlyio.atlassian.net/browse/COL-235
Description:
Changed the access token model for token based authentication. `from oauth2_provider.models import AccessToken` is not working on staging server. Now it is updated to `from provider.oauth2.models import AccessToken`.
=> changed access token model in custom authenticator of xblock api

openedx/features/colaraz_features/api/views.py
Ticket:
https://edlyio.atlassian.net/browse/COL-243
Description:
Added a flag to hide user navigation bar in xblock api response.
=> added a flag to hide user navigation bar in xblock

cms/envs/common.py
ticket:
https://edlyio.atlassian.net/browse/COL-244
Description:
Usage id pattern was missing in cms' common.py file which was raising error while running build.
=> added usage id pattern in cms common file

openedx/features/colaraz_features/auth_backend.py
**Resolved UnicodeEncodeError**
Story: [COL-263](https://edlyio.atlassian.net/browse/COL-263?atlOrigin=eyJpIjoiYjNhODU3YmQzOTExNGZhZTliMmNkMjNlMGI5ZmFlYmYiLCJwIjoiaiJ9)
Issue: `UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 6: ordinal not in range(128)`
Error occurred during Unicode conversion to String so I have ignored all the unicode characters which might cause issue.
=> Resolved UnicodeEncodeError

openedx/features/colaraz_features/api/views.py
Ticket: [COL-281](https://edlyio.atlassian.net/browse/COL-281)
- We found in the logs that sometimes requests got timed out when trying to get information from Colaraz APIs.
- Added generic exception handling to catch the error instead of throwing 500 error.
=> add general exceptional handling on colaraz apis

lms/djangoapps/instructor_task/tasks_helper/grades.py
In Grade Report, grades were showing in decimal values, so it is changed to display in percentage.
=> COL-285 Display grades in percentage in grade report

lms/envs/common.py
Changing limit in the SGA block wasn't working as nginx was blocking the larger files, eventually, we have to override this limit in the edx-platform.
=> fix: upload file limit

lms/templates/vert_module.html
CSV files were changing to xls on download. Issue is fixed and now CSVs will be downloaded with correct format.
=> Wrong format for CSV files on download issue fixed
